import { Review } from '../../../types/review';

export const mockHostawayReviews: Review[] = [
  // January 2025 - High season, more reviews
  {
    id: '7453',
    listingId: '1',
    rating: null,
    comment: 'Shane and family are wonderful! Would definitely host again :)',
    guestName: 'Shane Finkelstein',
    date: '2020-08-21 22:45:14',
    reviewType: 'host-to-guest',
    channel: 'hostaway',
    source: 'hostaway',
    status: 'published',
    reviewCategory: [
      {
        category: 'cleanliness',
        rating: 10
      },
      {
        category: 'communication',
        rating: 10
      },
      {
        category: 'respect_house_rules',
        rating: 10
      }
    ],
    listingName: '2B N1 A - 29 Shoreditch Heights',
    approved: true,
  },
  {
    id: 'hostaway-2',
    listingId: '1',
    rating: null,
    comment: 'Great place to stay! Clean, well-maintained, and in a prime location. Only minor issue was the WiFi connection being a bit slow at peak hours.',
    guestName: 'Michael Chen',
    date: '2025-01-10 09:15:00',
    reviewType: 'guest-to-host',
    channel: 'hostaway',
    source: 'hostaway',
    status: 'published',
    reviewCategory: [
      { category: 'cleanliness', rating: 8 },
      { category: 'communication', rating: 9 },
      { category: 'respect_house_rules', rating: 9 }
    ],
    listingName: 'Luxury Downtown Apartment',
    approved: true,
  },
  {
    id: 'hostaway-3',
    listingId: '2',
    rating: null,
    comment: 'Perfect getaway spot. The amenities were top-notch and the host provided excellent recommendations for local attractions. The kitchen was fully equipped.',
    guestName: 'Emma Rodriguez',
    date: '2025-01-08 16:45:00',
    reviewType: 'guest-to-host',
    channel: 'hostaway',
    source: 'hostaway',
    status: 'published',
    reviewCategory: [
      { category: 'cleanliness', rating: 10 },
      { category: 'communication', rating: 10 },
      { category: 'respect_house_rules', rating: 10 }
    ],
    listingName: 'Cozy Mountain Cabin',
    approved: true,
  },
  {
    id: 'hostaway-4',
    listingId: '3',
    rating: null,
    comment: 'Very comfortable stay with great amenities. The bed was incredibly comfortable and the room had plenty of natural light. Would definitely recommend to friends.',
    guestName: 'James Wilson',
    date: '2025-01-22 10:30:00',
    reviewType: 'guest-to-host',
    channel: 'hostaway',
    source: 'hostaway',
    status: 'published',
    reviewCategory: [
      { category: 'cleanliness', rating: 9 },
      { category: 'communication', rating: 8 },
      { category: 'respect_house_rules', rating: 9 }
    ],
    listingName: 'Modern City Loft',
    approved: true,
  },
  {
    id: 'hostaway-5',
    listingId: '1',
    rating: null,
    comment: 'Outstanding property management. Everything was handled professionally and efficiently. The check-in process was seamless.',
    guestName: 'Anna Kowalski',
    date: '2025-01-28 15:45:00',
    reviewType: 'host-to-guest',
    channel: 'hostaway',
    source: 'hostaway',
    status: 'published',
    reviewCategory: [
      { category: 'cleanliness', rating: 10 },
      { category: 'communication', rating: 10 },
      { category: 'respect_house_rules', rating: 10 }
    ],
    listingName: 'Luxury Downtown Apartment',
    approved: true,
  },

  // February 2025 - Valentine's season
  {
    id: 'hostaway-6',
    listingId: '2',
    rating: null,
    comment: 'Romantic getaway was perfect! The property had such a cozy atmosphere with beautiful natural lighting. The host even left champagne and chocolates for our anniversary.',
    guestName: 'David Thompson',
    date: '2025-02-14 19:20:00',
    reviewType: 'guest-to-host',
    channel: 'hostaway',
    source: 'hostaway',
    status: 'published',
    reviewCategory: [
      { category: 'cleanliness', rating: 10 },
      { category: 'communication', rating: 10 },
      { category: 'respect_house_rules', rating: 10 }
    ],
    listingName: 'Cozy Mountain Cabin',
    approved: true,
  },
  {
    id: 'hostaway-7',
    listingId: '1',
    rating: null,
    comment: 'Decent accommodation but expected more given the price. The kitchen could use some updates and the heating was inconsistent.',
    guestName: 'Lisa Park',
    date: '2025-02-05 11:20:00',
    reviewType: 'guest-to-host',
    channel: 'hostaway',
    source: 'hostaway',
    status: 'published',
    reviewCategory: [
      { category: 'cleanliness', rating: 6 },
      { category: 'communication', rating: 7 },
      { category: 'respect_house_rules', rating: 8 }
    ],
    listingName: 'Luxury Downtown Apartment',
    approved: false,
  },
  {
    id: 'hostaway-8',
    listingId: '3',
    rating: null,
    comment: 'Exceptional experience! The property exceeded our expectations in every way. The views from the bedroom window were spectacular.',
    guestName: 'Robert Lee',
    date: '2025-02-18 13:10:00',
    reviewType: 'guest-to-host',
    channel: 'hostaway',
    source: 'hostaway',
    status: 'published',
    reviewCategory: [
      { category: 'cleanliness', rating: 10 },
      { category: 'communication', rating: 10 },
      { category: 'respect_house_rules', rating: 10 }
    ],
    listingName: 'Modern City Loft',
    approved: true,
  },
  {
    id: 'hostaway-9',
    listingId: '2',
    rating: null,
    comment: 'Good communication from the host. Property was clean upon arrival. The only issue was parking being a bit tight.',
    guestName: 'Maria Garcia',
    date: '2025-02-25 08:00:00',
    reviewType: 'guest-to-host',
    channel: 'hostaway',
    source: 'hostaway',
    status: 'published',
    reviewCategory: [
      { category: 'cleanliness', rating: 9 },
      { category: 'communication', rating: 8 },
      { category: 'respect_house_rules', rating: 9 }
    ],
    listingName: 'Cozy Mountain Cabin',
    approved: true,
  },

  // March 2025 - Spring break season
  {
    id: 'hostaway-10',
    listingId: '1',
    rating: null,
    comment: 'Fantastic location and amenities. Perfect for a business trip or leisure stay. The workspace was well-equipped with great lighting.',
    guestName: 'Carlos Mendoza',
    date: '2025-03-12 12:15:00',
    reviewType: 'guest-to-host',
    channel: 'hostaway',
    source: 'hostaway',
    status: 'published',
    reviewCategory: [
      { category: 'cleanliness', rating: 10 },
      { category: 'communication', rating: 10 },
      { category: 'respect_house_rules', rating: 10 }
    ],
    listingName: 'Luxury Downtown Apartment',
    approved: true,
  },
  {
    id: 'hostaway-11',
    listingId: '3',
    rating: null,
    comment: 'Wonderful stay with excellent service. The host was very accommodating and provided great local recommendations.',
    guestName: 'Jennifer Liu',
    date: '2025-03-08 16:30:00',
    reviewType: 'guest-to-host',
    channel: 'hostaway',
    source: 'hostaway',
    status: 'published',
    reviewCategory: [
      { category: 'cleanliness', rating: 9 },
      { category: 'communication', rating: 8 },
      { category: 'respect_house_rules', rating: 9 }
    ],
    listingName: 'Modern City Loft',
    approved: true,
  },
  {
    id: 'hostaway-12',
    listingId: '2',
    rating: null,
    comment: 'Disappointing experience. The property did not match the description and there were maintenance issues. The photos were misleading.',
    guestName: 'Thomas Brown',
    date: '2025-03-15 14:20:00',
    reviewType: 'guest-to-host',
    channel: 'hostaway',
    source: 'hostaway',
    status: 'published',
    reviewCategory: [
      { category: 'cleanliness', rating: 4 },
      { category: 'communication', rating: 3 },
      { category: 'respect_house_rules', rating: 5 }
    ],
    listingName: 'Cozy Mountain Cabin',
    approved: false,
  },
  {
    id: 'hostaway-13',
    listingId: '1',
    rating: null,
    comment: 'Perfect location for exploring the city. Highly recommend this property! The natural light throughout the day was amazing.',
    guestName: 'Sophie Anderson',
    date: '2025-03-22 11:45:00',
    reviewType: 'guest-to-host',
    channel: 'hostaway',
    source: 'hostaway',
    status: 'published',
    reviewCategory: [
      { category: 'cleanliness', rating: 10 },
      { category: 'communication', rating: 10 },
      { category: 'respect_house_rules', rating: 10 }
    ],
    listingName: 'Luxury Downtown Apartment',
    approved: true,
  },
  {
    id: 'hostaway-14',
    listingId: '3',
    rating: null,
    comment: 'Great value for money. Clean, comfortable, and well-equipped. The host responded quickly to our questions.',
    guestName: 'Marcus Johnson',
    date: '2025-03-28 13:30:00',
    reviewType: 'guest-to-host',
    channel: 'hostaway',
    source: 'hostaway',
    status: 'published',
    reviewCategory: [
      { category: 'cleanliness', rating: 8 },
      { category: 'communication', rating: 9 },
      { category: 'respect_house_rules', rating: 9 }
    ],
    listingName: 'Modern City Loft',
    approved: true,
  },

  // April 2025 - Easter holiday
  {
    id: 'hostaway-15',
    listingId: '2',
    rating: null,
    comment: 'Exceeded all expectations! Beautiful property with amazing views. The Easter decorations were a nice touch.',
    guestName: 'Isabella Rossi',
    date: '2025-04-18 09:20:00',
    reviewType: 'guest-to-host',
    channel: 'hostaway',
    source: 'hostaway',
    status: 'published',
    reviewCategory: [
      { category: 'cleanliness', rating: 10 },
      { category: 'communication', rating: 10 },
      { category: 'respect_house_rules', rating: 10 }
    ],
    listingName: 'Cozy Mountain Cabin',
    approved: true,
  },
  {
    id: 'hostaway-16',
    listingId: '1',
    rating: null,
    comment: 'Very pleasant stay. The property was well-maintained and the location was convenient. Minor issue with noise from nearby construction.',
    guestName: 'Ahmed Hassan',
    date: '2025-04-10 17:45:00',
    reviewType: 'guest-to-host',
    channel: 'hostaway',
    source: 'hostaway',
    status: 'published',
    reviewCategory: [
      { category: 'cleanliness', rating: 8 },
      { category: 'communication', rating: 9 },
      { category: 'respect_house_rules', rating: 8 }
    ],
    listingName: 'Luxury Downtown Apartment',
    approved: true,
  },
  {
    id: 'hostaway-17',
    listingId: '3',
    rating: null,
    comment: 'Average experience. The property was okay but needs some maintenance work. The furniture showed signs of wear.',
    guestName: 'Nina Petrov',
    date: '2025-04-22 14:15:00',
    reviewType: 'guest-to-host',
    channel: 'hostaway',
    source: 'hostaway',
    status: 'published',
    reviewCategory: [
      { category: 'cleanliness', rating: 6 },
      { category: 'communication', rating: 7 },
      { category: 'respect_house_rules', rating: 6 }
    ],
    listingName: 'Modern City Loft',
    approved: false,
  },

  // May 2025 - Bank holiday
  {
    id: 'hostaway-18',
    listingId: '1',
    rating: null,
    comment: 'Outstanding hospitality and property quality. Will definitely return! The breakfast recommendations were spot on.',
    guestName: 'Diego Silva',
    date: '2025-05-05 08:30:00',
    reviewType: 'guest-to-host',
    channel: 'hostaway',
    source: 'hostaway',
    status: 'published',
    reviewCategory: [
      { category: 'cleanliness', rating: 10 },
      { category: 'communication', rating: 10 },
      { category: 'respect_house_rules', rating: 10 }
    ],
    listingName: 'Luxury Downtown Apartment',
    approved: true,
  },
  {
    id: 'hostaway-19',
    listingId: '2',
    rating: null,
    comment: 'Excellent stay with beautiful surroundings. The garden was particularly lovely and well-maintained.',
    guestName: 'Rachel Green',
    date: '2025-05-12 15:20:00',
    reviewType: 'guest-to-host',
    channel: 'hostaway',
    source: 'hostaway',
    status: 'published',
    reviewCategory: [
      { category: 'cleanliness', rating: 8 },
      { category: 'communication', rating: 9 },
      { category: 'respect_house_rules', rating: 8 }
    ],
    listingName: 'Cozy Mountain Cabin',
    approved: true,
  },
  {
    id: 'hostaway-20',
    listingId: '3',
    rating: null,
    comment: 'Perfect for our bank holiday getaway. The property was immaculate and the host was incredibly helpful.',
    guestName: 'Kevin Zhang',
    date: '2025-05-26 11:10:00',
    reviewType: 'guest-to-host',
    channel: 'hostaway',
    source: 'hostaway',
    status: 'published',
    reviewCategory: [
      { category: 'cleanliness', rating: 10 },
      { category: 'communication', rating: 10 },
      { category: 'respect_house_rules', rating: 10 }
    ],
    listingName: 'Modern City Loft',
    approved: true,
  },

  // June 2025 - Summer season begins
  {
    id: 'hostaway-21',
    listingId: '1',
    rating: null,
    comment: 'Great summer stay! The property was cool and comfortable despite the heat. The air conditioning worked perfectly.',
    guestName: 'Olivia Martin',
    date: '2025-06-08 16:45:00',
    reviewType: 'guest-to-host',
    channel: 'hostaway',
    source: 'hostaway',
    status: 'published',
    reviewCategory: [
      { category: 'cleanliness', rating: 8 },
      { category: 'communication', rating: 9 },
      { category: 'respect_house_rules', rating: 8 }
    ],
    listingName: 'Luxury Downtown Apartment',
    approved: true,
  },
  {
    id: 'hostaway-22',
    listingId: '2',
    rating: null,
    comment: 'Amazing property for a summer vacation. The pool area was fantastic and the outdoor space was perfect for evening BBQs.',
    guestName: 'Lucas Weber',
    date: '2025-06-15 13:25:00',
    reviewType: 'guest-to-host',
    channel: 'hostaway',
    source: 'hostaway',
    status: 'published',
    reviewCategory: [
      { category: 'cleanliness', rating: 10 },
      { category: 'communication', rating: 10 },
      { category: 'respect_house_rules', rating: 10 }
    ],
    listingName: 'Cozy Mountain Cabin',
    approved: true,
  },
  {
    id: 'hostaway-23',
    listingId: '3',
    rating: null,
    comment: 'Decent property but overpriced for what it offers. The garden needed maintenance and some facilities were outdated.',
    guestName: 'Priya Sharma',
    date: '2025-06-22 10:15:00',
    reviewType: 'guest-to-host',
    channel: 'hostaway',
    source: 'hostaway',
    status: 'published',
    reviewCategory: [
      { category: 'cleanliness', rating: 6 },
      { category: 'communication', rating: 7 },
      { category: 'respect_house_rules', rating: 6 }
    ],
    listingName: 'Modern City Loft',
    approved: false,
  },
  {
    id: 'hostaway-24',
    listingId: '1',
    rating: null,
    comment: 'Automated review: Guest checkout completed successfully. Property left in excellent condition.',
    guestName: 'System',
    date: '2025-06-16 10:00:00',
    reviewType: 'automatic',
    channel: 'hostaway',
    source: 'hostaway',
    status: 'published',
    reviewCategory: [],
    listingName: 'Luxury Downtown Apartment',
    approved: true,
  },

  // July 2025 - Peak summer
  {
    id: 'hostaway-25',
    listingId: '2',
    rating: null,
    comment: 'Perfect summer holiday destination! The property was ideal for our family with young children. Plenty of space and great facilities.',
    guestName: 'Hannah Clarke',
    date: '2025-07-04 14:30:00',
    reviewType: 'guest-to-host',
    channel: 'hostaway',
    source: 'hostaway',
    status: 'published',
    reviewCategory: [
      { category: 'cleanliness', rating: 10 },
      { category: 'communication', rating: 10 },
      { category: 'respect_house_rules', rating: 10 }
    ],
    listingName: 'Cozy Mountain Cabin',
    approved: true,
  },
  {
    id: 'hostaway-26',
    listingId: '1',
    rating: null,
    comment: 'Excellent location for summer activities. Close to beaches and local attractions. The property was clean and well-equipped.',
    guestName: 'Mohammed Al-Rashid',
    date: '2025-07-12 09:45:00',
    reviewType: 'guest-to-host',
    channel: 'hostaway',
    source: 'hostaway',
    status: 'published',
    reviewCategory: [
      { category: 'cleanliness', rating: 8 },
      { category: 'communication', rating: 9 },
      { category: 'respect_house_rules', rating: 8 }
    ],
    listingName: 'Luxury Downtown Apartment',
    approved: true,
  },
  {
    id: 'hostaway-27',
    listingId: '3',
    rating: null,
    comment: 'Outstanding property with amazing amenities. The outdoor kitchen was perfect for summer entertaining.',
    guestName: 'Elena Dimitriadis',
    date: '2025-07-18 17:20:00',
    reviewType: 'guest-to-host',
    channel: 'hostaway',
    source: 'hostaway',
    status: 'published',
    reviewCategory: [
      { category: 'cleanliness', rating: 10 },
      { category: 'communication', rating: 10 },
      { category: 'respect_house_rules', rating: 10 }
    ],
    listingName: 'Modern City Loft',
    approved: true,
  },
  {
    id: 'hostaway-28',
    listingId: '2',
    rating: null,
    comment: 'Great value summer rental. The property was spacious and the garden was beautiful. Minor issue with the WiFi during peak hours.',
    guestName: 'Tom Harrison',
    date: '2025-07-25 12:10:00',
    reviewType: 'guest-to-host',
    channel: 'hostaway',
    source: 'hostaway',
    status: 'published',
    reviewCategory: [
      { category: 'cleanliness', rating: 8 },
      { category: 'communication', rating: 9 },
      { category: 'respect_house_rules', rating: 8 }
    ],
    listingName: 'Cozy Mountain Cabin',
    approved: true,
  },

  // August 2025 - Peak summer continued
  {
    id: 'hostaway-29',
    listingId: '1',
    rating: null,
    comment: 'Fantastic summer vacation! The property exceeded our expectations. The host was very responsive and helpful.',
    guestName: 'Yuki Tanaka',
    date: '2025-08-02 15:35:00',
    reviewType: 'guest-to-host',
    channel: 'hostaway',
    source: 'hostaway',
    status: 'published',
    reviewCategory: [
      { category: 'cleanliness', rating: 10 },
      { category: 'communication', rating: 10 },
      { category: 'respect_house_rules', rating: 10 }
    ],
    listingName: 'Luxury Downtown Apartment',
    approved: true,
  },
  {
    id: 'hostaway-30',
    listingId: '3',
    rating: null,
    comment: 'Very comfortable summer stay. The air conditioning was excellent and the property was well-shaded.',
    guestName: 'Fatima Al-Zahra',
    date: '2025-08-09 11:50:00',
    reviewType: 'guest-to-host',
    channel: 'hostaway',
    source: 'hostaway',
    status: 'published',
    reviewCategory: [
      { category: 'cleanliness', rating: 8 },
      { category: 'communication', rating: 9 },
      { category: 'respect_house_rules', rating: 8 }
    ],
    listingName: 'Modern City Loft',
    approved: true,
  },
  {
    id: 'hostaway-31',
    listingId: '2',
    rating: null,
    comment: 'Average summer rental. The property was okay but the maintenance could be better. Some facilities were not working properly.',
    guestName: 'Pierre Dubois',
    date: '2025-08-16 08:25:00',
    reviewType: 'guest-to-host',
    channel: 'hostaway',
    source: 'hostaway',
    status: 'published',
    reviewCategory: [
      { category: 'cleanliness', rating: 6 },
      { category: 'communication', rating: 7 },
      { category: 'respect_house_rules', rating: 6 }
    ],
    listingName: 'Cozy Mountain Cabin',
    approved: false,
  },
  {
    id: 'hostaway-32',
    listingId: '1',
    rating: null,
    comment: 'Perfect end-of-summer getaway! The property was immaculate and the location was ideal for our activities.',
    guestName: 'Anna Schmidt',
    date: '2025-08-23 13:40:00',
    reviewType: 'guest-to-host',
    channel: 'hostaway',
    source: 'hostaway',
    status: 'published',
    reviewCategory: [
      { category: 'cleanliness', rating: 10 },
      { category: 'communication', rating: 10 },
      { category: 'respect_house_rules', rating: 10 }
    ],
    listingName: 'Luxury Downtown Apartment',
    approved: true,
  },
  {
    id: 'hostaway-33',
    listingId: '3',
    rating: null,
    comment: 'Excellent property for a late summer break. Clean, comfortable, and well-equipped. The garden was particularly lovely.',
    guestName: 'Miguel Santos',
    date: '2025-08-30 16:15:00',
    reviewType: 'guest-to-host',
    channel: 'hostaway',
    source: 'hostaway',
    status: 'published',
    reviewCategory: [
      { category: 'cleanliness', rating: 8 },
      { category: 'communication', rating: 9 },
      { category: 'respect_house_rules', rating: 8 }
    ],
    listingName: 'Modern City Loft',
    approved: true,
  },

  // September 2025 - Back to school season
  {
    id: 'hostaway-34',
    listingId: '2',
    rating: null,
    comment: 'Wonderful property for our family reunion. Plenty of space, great amenities, and the host was very accommodating.',
    guestName: 'Grace O\'Connor',
    date: '2025-09-06 10:20:00',
    reviewType: 'guest-to-host',
    channel: 'hostaway',
    source: 'hostaway',
    status: 'published',
    reviewCategory: [
      { category: 'cleanliness', rating: 10 },
      { category: 'communication', rating: 10 },
      { category: 'respect_house_rules', rating: 10 }
    ],
    listingName: 'Cozy Mountain Cabin',
    approved: true,
  },
  {
    id: 'hostaway-35',
    listingId: '1',
    rating: null,
    comment: 'Great value property. Clean and comfortable with good amenities. Perfect for a quiet weekend getaway.',
    guestName: 'Raj Patel',
    date: '2025-09-13 14:55:00',
    reviewType: 'guest-to-host',
    channel: 'hostaway',
    source: 'hostaway',
    status: 'published',
    reviewCategory: [
      { category: 'cleanliness', rating: 8 },
      { category: 'communication', rating: 9 },
      { category: 'respect_house_rules', rating: 8 }
    ],
    listingName: 'Luxury Downtown Apartment',
    approved: true,
  },
  {
    id: 'hostaway-36',
    listingId: '3',
    rating: null,
    comment: 'Outstanding property with excellent facilities. The host provided great recommendations for local restaurants.',
    guestName: 'Chiara Romano',
    date: '2025-09-20 12:30:00',
    reviewType: 'guest-to-host',
    channel: 'hostaway',
    source: 'hostaway',
    status: 'published',
    reviewCategory: [
      { category: 'cleanliness', rating: 10 },
      { category: 'communication', rating: 10 },
      { category: 'respect_house_rules', rating: 10 }
    ],
    listingName: 'Modern City Loft',
    approved: true,
  },
  {
    id: 'hostaway-37',
    listingId: '2',
    rating: null,
    comment: 'Very pleasant stay. The property was well-maintained and the location was convenient for our purposes.',
    guestName: 'Omar Al-Farsi',
    date: '2025-09-27 09:10:00',
    reviewType: 'guest-to-host',
    channel: 'hostaway',
    source: 'hostaway',
    status: 'published',
    reviewCategory: [
      { category: 'cleanliness', rating: 8 },
      { category: 'communication', rating: 9 },
      { category: 'respect_house_rules', rating: 8 }
    ],
    listingName: 'Cozy Mountain Cabin',
    approved: true,
  },
];
